server:
  port: 2335

spring:
  application:
    name: orangecloud-eureka

eureka:
  instance:
    hostname: orangecloud2.net
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://orangecloud1.net:2334/eureka/